#!/bin/bash

echo "Build with maven using codeql profile"
mvn -Pcodeql -B -V -e -Denforcer.skip -DskipTests clean package
echo "Remove 'Generated by delombok' lines from source files"
find target/generated-sources/delombok -name '*.java' -exec sed '/Generated by delombok/d' -i '{}' ';'
find target/generated-test-sources/delombok -name '*.java' -exec sed '/Generated by delombok/d' -i '{}' ';'
echo "Copy delomboked files back to original source directories"
cp -R target/generated-sources/delombok/* src/main/java/
echo "First lines of Property.java which should be the delomboked version:"
head src/main/java/org/kiwiproject/dynamicproperties/Property.java
cp -R target/generated-test-sources/delombok/* src/test/java/
echo "First lines of Department.java which should be the delomboked version:"
cat src/test/java/org/kiwiproject/dynamicproperties/data/Department.java
